version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build --tag cv --output . .
      - store_artifacts:
          path: cv.pdf
      - store_artifacts:
          path: cv-extended.pdf

workflows:
  version: 2
  build:
    jobs:
      - build